### ISSUE TITLE
JS > Browser compatibility

### ISSUE THREAD

**Issue by johannpinson** [greeeg/hetic-p2020-10#5]
Be careful, IntersectionObserver isn't compatible with IE/Safari

Use the polyfill or any equivalent configuration: https://github.com/w3c/IntersectionObserver/tree/master/polyfill

https://github.com/greeeg/hetic-p2020-10/blob/69580ff1decfffd2a856b0658be2c6eb1c85d0d3/src/js/components/utils.js#L8

**Comment by johannpinson** [comment]
Ok got it, you make the import inside "app.js" and not "utils.js"

The import must be moved where you need it.

**Comment by greeeg** [comment]
That's why we imported a polyfill before anything else available as a [NPM package](https://www.npmjs.com/package/intersection-observer).
 https://github.com/greeeg/hetic-p2020-10/blob/69580ff1decfffd2a856b0658be2c6eb1c85d0d3/src/js/app.js#L2
